common: &default_settings
  adapter: postgresql
  database: <%= ENV["DB_NAME"] || "alexa-stib-next-ride" %>
  host: <%= ENV["DB_HOST"] %>
  user: bluesquare
  port: <%= ENV["DB_PORT"] || 5432 %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: 50

development:
  <<: *default_settings

test:
  <<: *default_settings
  database: "alexa-stib-next-ride-test"

production:
  <<: *default_settings
